### ISSUE TITLE
examples/work-item-plugin typecheck fails on `rawText` (post-#51 PredicateWord field) — not caught by CI

### ISSUE THREAD

**Issue by cad0p** [cad0p/pi-steering#60]
Found 2026-08-19 while verifying the #54 follow-up landscape. Pre-existing, unrelated to #54 (present on main `242f3e4`).

## Problem

`pnpm --filter @examples/work-item-plugin typecheck` fails with 16 `TS2741` errors, all in `examples/work-item-plugin/src/predicates/work-item-format.test.ts`:

```
src/predicates/work-item-format.test.ts(41,18): error TS2741: Property 'rawText' is missing in type 'Word' but required in type 'PredicateWord'.
```

Root cause: the test's local fixture helper `W(value: string)` builds a `Word` as `{ value, text, pos, end }` — but `PredicateWord` gained a REQUIRED `rawText` field in #51 (`46f5c93`, "resolved-by-default Word.text"). `input.args` is typed `PredicateWord[]` (quote-aware structured access), so the fixture no longer satisfies the type. The example plugin is the canonical reference for plugin authors (ADR §15) — its test fixture is the one place that hand-constructs `Word`s and now lies about the shape.

## Why CI misses it

CI's example step runs `pnpm -r test` only (plus the pretest build); the `typecheck:examples` script (`pnpm -r typecheck`) is local-only. The `node --test` run passes because the fixture's missing `rawText` is a TYPE-only gap — runtime behavior is unaffected. So the example package has been type-broken since #51 without any red CI.

## Fix (small)

Add `rawText` to the `W()` helper — or, cleaner, build the fixture from the real walker shape (e.g. `rawText: value` mirroring what the evaluator emits). Optionally also add `typecheck:examples` (or a `tsc --noEmit` on examples) to CI so the canonical example can't drift again.

## Verification

- Reproduced on main `242f3e4`: stale `dist/` (Aug 16) initially showed ~34 errors incl. `missing`/when-clause noise; after `pnpm build` the ONLY remaining errors are the 16 `rawText` TS2741s in the one test file.
- Root package `tsc --noEmit` is 0 errors; example `tsc --noEmit` is 16 errors, all the same family.
